Entities/Category.cs
using System.Collections.Generic;

namespace Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IconUrl { get; set; }
        public List<Product> Products { get ;set; } = new List<Product>();
    }
}

Controllers/AdminPanelController.cs
using Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Controllers
{
    
    public class AdminPanelController : Controller
    {
        private IConfiguration _config;

        public AdminPanelController(IConfiguration config)
        {
            _config = config;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }
        [UserHaveSecretFilterAtrribute]
        [HttpGet]
        public IActionResult Category()
        {
            return View();
        }
        [UserHaveSecretFilterAtrribute]
        [HttpGet]
        public IActionResult Product()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([FromForm] Models.AdminPanelLoginModel model)
        {
            if(!(model.Login==_config.GetValue<string>("AdminPanel:Login") && model.Password==_config.GetValue<string>("AdminPanel:Password"))) 
                return Redirect("~/");
            HttpContext.Session.SetString("SecretCodeAdminPanel", _config.GetValue<string>("AdminPanel:SecretCode"));
            return Redirect("~/AdminPanelProduct/Products");
        }
    }
}

Controllers/CategoryController.cs
using System.Threading.Tasks;
using Filters;
using Interfaces;
using Laguna.Tools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Models;

namespace Controllers
{
    [UserHaveSecretFilterAtrribute]
    public class CategoryController : Controller
    {
        ICategoryService _service;
        IMemoryCache _memoryCache;

        public CategoryController(ICategoryService service, IMemoryCache memoryCache)
        {
            _service = service;
            _memoryCache = memoryCache;
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategories([FromForm] CreateCategoryModel model)
        {   
            if(!ModelState.IsValid) return BadRequest(model);
            _memoryCache.Remove(CacheKeys.Categories);
            return Ok(await _service.CreateCategory(model));
        } 
    
        [HttpPost]
        public async Task<IActionResult> ChangeCategory([FromForm] ChangeCategoryModel model)
        {   
            if(!ModelState.IsValid) return BadRequest(model);
            _memoryCache.Remove(CacheKeys.Categories);
            await _service.ChangeCategory(model);
            return Ok();
        }
      
        [HttpPost]
        public async Task<IActionResult> DeleteCategory([FromBody] DeleteCategoryModel model)
        {   
            if(!ModelState.IsValid) return BadRequest(model);
            _memoryCache.Remove(CacheKeys.Categories);
            await _service.Delete(model.Id);
            return Ok();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


    }
}

Views/AdminPanel/Category.cshtml
<!DOCTYPE html>
<html>
    <head>
               
    </head>
    <body>
       <div>
           <h1>Добавление</h1>
           <input type="text" id="add-name" placeholder="Введите название">
           <input type="file" id="add-file">
           <button id="add-button">Добавить</button>
       </div>
        <br>
       <div>
           <h1>Изменение</h1>
           <select id="change-select" class="select-category">
               <option value="0">--Выберите--</option>
                @foreach (var item in ViewBag.Categories)
                {
                    <option value="@item.Id" >@item.Name</option>
                }
           </select>
           <input id="change-name" type="text" placeholder="Введите новое название">
           <input type="file" id="change-file">
           <button id="change-button">Изменить</button>
       </div>
       <br>
       <div>
            <h1>Удаление</h1>
            <select id="del-select" class="select-category">
               <option value="0">--Выберите--</option>
                @foreach (var item in ViewBag.Categories)
                {
                    <option value="@item.Id" >@item.Name</option>
                }
            </select>
            <button id="del-button">Удалить</button>
       </div>
    <script src="~/js/CategoryAdminPanel/CategoryCreate.js"asp-append-version="true" ></script>
    <script src="~/js/CategoryAdminPanel/CategoryChange.js"asp-append-version="true" ></script>
    <script src="~/js/CategoryAdminPanel/CetegoryDelete.js"asp-append-version="true"></script>
    </body>
</html>

Views/AdminPanel/Login.cshtml
@model Models.AdminPanelLoginModel

<h2>Вход на сайт</h2>
 
 
<form asp-action="Login" asp-controller="AdminPanel" asp-anti-forgery="true">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div class="form-group">
            <label asp-for="Login">Введите Email</label>
            <input type="text" asp-for="Login" />
            <span asp-validation-for="Login" />
        </div>
        <div class="form-group">
            <label asp-for="Password">Введите пароль</label>
            <input asp-for="Password" />
            <span asp-validation-for="Password" />
        </div>
        <div class="form-group">
            <input type="submit" value="Войти" class="btn btn-primary" />
        </div>
    </div>
</form>